# Python Web Scraping: Extract and display all the header tags from en.wikipedia.org/wiki/Main_Page

In [1]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import os

In [2]:
page=requests.get('https://en.wikipedia.org/wiki/Main_Page')
page

In [3]:
html = urlopen('https://en.wikipedia.org/wiki/Main_Page')
bs = BeautifulSoup(html, "html.parser")
titles = bs.find_all(['h1', 'h2','h3','h4','h5','h6'])
print('List all the header tags :', *titles, sep='\n\n')

List all the header tags :

<h1 class="firstHeading" id="firstHeading">Main Page</h1>

<h2 class="mp-h2" id="mp-tfa-h2"><span id="From_today.27s_featured_article"></span><span class="mw-headline" id="From_today's_featured_article">From today's featured article</span></h2>

<h2 class="mp-h2" id="mp-dyk-h2"><span class="mw-headline" id="Did_you_know_...">Did you know ...</span></h2>

<h2 class="mp-h2" id="mp-itn-h2"><span class="mw-headline" id="In_the_news">In the news</span></h2>

<h2 class="mp-h2" id="mp-otd-h2"><span class="mw-headline" id="On_this_day">On this day</span></h2>

<h2 class="mp-h2" id="mp-tfp-h2"><span id="Today.27s_featured_picture"></span><span class="mw-headline" id="Today's_featured_picture">Today's featured picture</span></h2>

<h2 class="mp-h2" id="mp-other"><span class="mw-headline" id="Other_areas_of_Wikipedia">Other areas of Wikipedia</span></h2>

<h2 class="mp-h2" id="mp-sister"><span id="Wikipedia.27s_sister_projects"></span><span class="mw-headline" id="Wikipedia's_sister_projects">Wikipedia's sister projects</span></h2>

<h2 class="mp-h2" id="mp-lang"><span class="mw-headline" id="Wikipedia_languages">Wikipedia languages</span></h2>

<h2>Navigation menu</h2>

<h3 class="vector-menu-heading" id="p-personal-label">
<span>Personal tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-namespaces-label">
<span>Namespaces</span>
</h3>

<h3 class="vector-menu-heading" id="p-variants-label">
<span>Variants</span>
</h3>

<h3 class="vector-menu-heading" id="p-views-label">
<span>Views</span>
</h3>

<h3 class="vector-menu-heading" id="p-cactions-label">
<span>More</span>
</h3>

<h3>
<label for="searchInput">Search</label>
</h3>

<h3 class="vector-menu-heading" id="p-navigation-label">
<span>Navigation</span>
</h3>

<h3 class="vector-menu-heading" id="p-interaction-label">
<span>Contribute</span>
</h3>

<h3 class="vector-menu-heading" id="p-tb-label">
<span>Tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-coll-print_export-label">
<span>Print/export</span>
</h3>

<h3 class="vector-menu-heading" id="p-wikibase-otherprojects-label">
<span>In other projects</span>
</h3>

<h3 class="vector-menu-heading" id="p-lang-label">
<span>Languages</span>
</h3>

# python program to display IMDB’s Top rated 100 movies’ data (i.e. Name, IMDB rating, Year of release) and make data frame.

In [4]:
df = pd.read_csv('Top 100 Movies List.csv')
print("Columns of the DataFrame:")
print(df.columns)

Columns of the DataFrame:
Index(['Position', 'Const', 'Created', 'Modified', 'Description', 'Title',
       'URL', 'Title Type', 'IMDb Rating', 'Runtime (mins)', 'Year', 'Genres',
       'Num Votes', 'Release Date', 'Directors'],
      dtype='object')

In [5]:
df

,Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
0,1,tt0111161,2019-11-21,2019-11-21,NaN,The Shawshank Redemption,https://www.imdb.com/title/tt0111161/,movie,9.3,142,1994,Drama,2395359,1994-09-10,Frank Darabont
1,2,tt0068646,2019-11-21,2019-11-21,NaN,The Godfather,https://www.imdb.com/title/tt0068646/,movie,9.2,175,1972,"Crime, Drama",1659267,1972-03-14,Francis Ford Coppola
2,3,tt0071562,2019-11-21,2019-11-21,NaN,The Godfather: Part II,https://www.imdb.com/title/tt0071562/,movie,9.0,202,1974,"Crime, Drama",1153446,1974-12-12,Francis Ford Coppola
3,4,tt0468569,2019-11-21,2019-11-21,NaN,The Dark Knight,https://www.imdb.com/title/tt0468569/,movie,9.0,152,2008,"Action, Crime, Drama, Thriller",2357045,2008-07-14,Christopher Nolan
4,5,tt0050083,2019-11-21,2019-11-21,NaN,12 Angry Men,https://www.imdb.com/title/tt0050083/,movie,9.0,96,1957,"Crime, Drama",706419,1957-04-10,Sidney Lumet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,tt0053125,2019-11-21,2019-11-21,NaN,North by Northwest,https://www.imdb.com/title/tt0053125/,movie,8.3,136,1959,"Adventure, Mystery, Thriller",303925,1959-07-01,Alfred Hitchcock
96,97,tt0066921,2019-11-21,2019-11-21,NaN,A Clockwork Orange,https://www.imdb.com/title/tt0066921/,movie,8.3,136,1971,"Crime, Drama, Sci-Fi",769919,1971-12-19,Stanley Kubrick
97,98,tt0208092,2019-11-21,2019-11-21,NaN,Snatch,https://www.imdb.com/title/tt0208092/,movie,8.3,104,2000,"Comedy, Crime",794621,2000-08-23,Guy Ritchie
98,99,tt0211915,2019-11-21,2019-11-21,NaN,Le fabuleux destin d'Amélie Poulain,https://www.imdb.com/title/tt0211915/,movie,8.3,122,2001,"Comedy, Romance",713713,2001-04-25,Jean-Pierre Jeunet
99,100,tt0012349,2019-11-21,2019-11-21,NaN,The Kid,https://www.imdb.com/title/tt0012349/,movie,8.3,68,1921,"Comedy, Drama, Family",116284,1921-01-16,Charles Chaplin

# python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. Name, IMDB rating, Year 
of release) and make data frame.

In [6]:
df = pd.read_csv('IMDB Top 100 Hindi Movies.csv')
print("Columns of the DataFrame:")
print(df.columns)

Columns of the DataFrame:
Index(['Position', 'Const', 'Created', 'Modified', 'Description', 'Title',
       'URL', 'Title Type', 'IMDb Rating', 'Runtime (mins)', 'Year', 'Genres',
       'Num Votes', 'Release Date', 'Directors'],
      dtype='object')

In [7]:
df

,Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
0,1,tt0405508,2012-07-24,2012-10-07,[b][link=http://www.youtube.com/watch?v=AK28V4...,Rang De Basanti,https://www.imdb.com/title/tt0405508/,movie,8.1,167,2006,"Comedy, Crime, Drama",114035,2006-01-26,Rakeysh Omprakash Mehra
1,2,tt1187043,2012-07-24,2012-10-07,Highest grosser in Bollywood history\n\n[b][li...,3 Idiots,https://www.imdb.com/title/tt1187043/,movie,8.4,170,2009,"Comedy, Drama",354884,2009-12-23,Rajkumar Hirani
2,3,tt0986264,2012-07-24,2012-10-07,[b][link=http://www.youtube.com/watch?v=2VdZUj...,Taare Zameen Par,https://www.imdb.com/title/tt0986264/,movie,8.4,165,2007,"Drama, Family",174559,2007-12-21,"Aamir Khan, Amole Gupte"
3,4,tt0292490,2012-07-24,2012-10-07,[b][link=http://www.youtube.com/watch?v=m13b25...,Dil Chahta Hai,https://www.imdb.com/title/tt0292490/,movie,8.1,183,2001,"Comedy, Drama, Romance",67814,2001-08-10,Farhan Akhtar
4,5,tt0367110,2012-07-24,2012-10-07,[b][link=http://www.youtube.com/watch?v=NC7Guo...,"Swades: We, the People",https://www.imdb.com/title/tt0367110/,movie,8.2,210,2004,Drama,84788,2004-12-17,Ashutosh Gowariker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,tt1324059,2013-08-25,2013-08-25,NaN,Wake Up Sid,https://www.imdb.com/title/tt1324059/,movie,7.6,138,2009,"Comedy, Drama, Romance",28921,2009-10-02,Ayan Mukherjee
96,97,tt0114234,2012-07-25,2012-07-25,NaN,Rangeela,https://www.imdb.com/title/tt0114234/,movie,7.5,142,1995,"Comedy, Drama, Musical, Romance",9326,1995-09-08,Ram Gopal Varma
97,98,tt0076696,2012-07-25,2012-10-09,From the legendary Oscar winning director Sat...,Shatranj Ke Khilari,https://www.imdb.com/title/tt0076696/,movie,7.7,129,1977,"Comedy, Drama, History",3256,1977-03-10,Satyajit Ray
98,99,tt1926313,2012-07-25,2012-10-07,[b][link=http://www.youtube.com/watch?v=7pFE44...,Pyaar Ka Punchnama,https://www.imdb.com/title/tt1926313/,movie,7.6,149,2011,"Comedy, Drama, Romance",20241,2011-05-20,Luv Ranjan
99,100,tt0352314,2013-09-23,2013-09-23,NaN,Ek Hasina Thi,https://www.imdb.com/title/tt0352314/,movie,7.5,120,2004,"Crime, Drama, Mystery, Thriller",6959,2004-01-16,Sriram Raghavan

# python program to scrap book name, author name, genre and book review of any 5 books from 
‘www.bookpage.com

In [173]:
import sys,requests,csv,io
from bs4 import BeautifulSoup
from urllib.parse import urljoin

def scrape_and_run(genre):
    # scrape on bookpage.com using desire genre type or key word
    # and save the titles and autors in a csv file
    page = requests.get("https://bookpage.com/features?book_genre=mystery&page=1" + genre)
    soup = bs(page.content, 'html.parser')
    title = soup.find_all('a', class_='bookTitle')
    authors = soup.find_all('a', class_='authorName')

In [174]:
with open('genre' + 'bookpage.csv', 'w') as csvfile:
        fieldnames = ['title', 'author']
        csv_write = csv.DictWriter(csvfile, fieldnames=fieldnames)
        books_save = 0

In [211]:
## single book page

url = "https://bookpage.com/"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

title = soup.select("#heroCarousel > div.carousel-inner > div.item.active > div > div.span6.hero-text > h4 > a")

for a in title:
    print(a.text)

Gallery of Beach-Worthy Books Giveaway

In [209]:
url = "https://bookpage.com/"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

title = soup.select("#heroCarousel > div.carousel-inner > div:nth-child(2) > div > div.span6.hero-text > h4 > a")
for a in title:
    print(a.text)

Bookshelf meet cute

In [204]:
url = "https://bookpage.com/"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

title = soup.select("#heroCarousel > div.carousel-inner > div:nth-child(3) > div > div.span6.hero-text > h4")
for a in title:
    print(a.text)

For kids: Great chapter books

In [223]:
import sys,requests,csv,io
from bs4 import BeautifulSoup
from urllib.parse import urljoin

url = "https://bookpage.com/features/26174-hold-list-bookshelf-meet-cute-fiction#.YLNZvo3itPY"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("body > div:nth-child(7) > div.page-content > div:nth-child(2) > div > div > div > div > div.span5 > div:nth-child(1)")
for a in anchors:
    print(div.text)

# python program to scrape cricket rankings from ‘www.icc-cricket.com’. You have to scrape:

In [56]:
#Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.

import sys,requests,csv,io
from bs4 import BeautifulSoup
from urllib.parse import urljoin

url = "https://www.icc-cricket.com/rankings/mens/team-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > section > div.rankings-block__container.full.rankings-table")
for a in anchors:
    print(a.text)

Pos

Team
T


Matches
M


Points
P


Rating
R





1


New Zealand
NZ

17
2,054

                            121





2


Australia
AUS

25
2,945
118


3


India
IND

29
3,344
115


4


England
ENG

27
3,100
115


5


South Africa
SA

20
2,137
107


6


Pakistan
PAK

24
2,323
97


7


Bangladesh
BAN

27
2,438
90


8


West Indies
WI

27
2,222
82


9


Sri Lanka
SL

24
1,876
78


10


Afghanistan
AFG

17
1,054
62


11


Ireland
IRE

18
818
45


12


Zimbabwe
ZIM

15
588
39


13


Netherlands
NED

4
154
39


14


Scotland
SCO

7
258
37


15


Oman
OMA

7
240
34


16


Nepal
NEP

5
119
24


17


UAE
UAE

9
190
21


18


Namibia
NAM

6
97
16


19


United States
USA

8
93
12


20


Papua New Guinea
PNG

5
0
0

In [13]:
#Top 10 ODI Batsmen in men along with the records of their team and rating

url = "https://www.icc-cricket.com/rankings/mens/player-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > section:nth-child(2) > div.u-negative-wrapper-tab.uniform-grid.touch-scroll-list--tablet > div:nth-child(1) > div")
for a in anchors:
    print(a.text)

odi
ODI Batting Rankings




Share
















URL Copied








                        1



Babar Azam


PAK
865













Pos
Player
Team
Rating





                                    2



Virat Kohli



IND

857



                                    3



Rohit Sharma



IND

825



                                    4



Ross Taylor



NZ

801



                                    5



Aaron Finch



AUS

791



                                    6



Jonny Bairstow



ENG

785



                                    7



Fakhar Zaman



PAK

778







Francois du Plessis



SA

778



                                    9



David Warner



AUS

773







Shai Hope



WI

773




Full Table

In [14]:
#Top 10 ODI bowlers along with the records of their team and rating.

url = "https://www.icc-cricket.com/rankings/mens/player-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > section:nth-child(2) > div.u-negative-wrapper-tab.uniform-grid.touch-scroll-list--tablet > div:nth-child(2) > div")
for a in anchors:
    print(a.text)

odi
ODI Bowling Rankings




Share
















URL Copied








                        1



Trent Boult


NZ
737













Pos
Player
Team
Rating





                                    2




This player has moved up in the rankings since the previous rankings update



Mehedi Hasan



BAN

725



                                    3




This player has moved down in the rankings since the previous rankings update



Mujeeb Ur Rahman



AFG

708



                                    4



Matt Henry



NZ

691



                                    5



Jasprit Bumrah



IND

690



                                    6



Kagiso Rabada



SA

666



                                    7



Chris Woakes



ENG

665



                                    8



Josh Hazlewood



AUS

660



                                    9




This player has moved up in the rankings since the previous rankings update



Mustafizur Rahman



BAN

652



                                    10




This player has moved down in the rankings since the previous rankings update



Pat Cummins



AUS

646




Full Table

# python program to scrape cricket rankings from ‘www.icc-cricket.com’. You have to scrape:

In [15]:
#Top 10 ODI teams in women’s cricket along with the records for matches, points and rating

url = "https://www.icc-cricket.com/rankings/womens/team-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > section")
for a in anchors:
    print(a.text)

wodi
Women's ODI Rankings


Last updated (GMT) - 11 Apr 2021
Developed by David Kendix





Pos

Team
T


Matches
M


Points
P


Rating
R





1


Australia
AUS

18
2,955

                            164





2


South Africa
SA

24
2,828
118


3


England
ENG

17
1,993
117


4


India
IND

20
2,226
111


5


New Zealand
NZ

21
1,947
93


6


West Indies
WI

12
1,025
85


7


Pakistan
PAK

15
1,101
73


8


Bangladesh
BAN

5
306
61


9


Sri Lanka
SL

11
519
47


10


Ireland
IRE

2
25
13

In [16]:
#Top 10 women’s ODI players along with the records of their team and rating.


url = "https://www.icc-cricket.com/rankings/womens/player-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > div > div")
for a in anchors:
    print(a.text)

wodi
ODI Batting Rankings




Share
















URL Copied








                        1



Tammy Beaumont


ENG
765













Pos
Player
Team
Rating





                                    2



Lizelle Lee



SA

758



                                    3



Alyssa Healy



AUS

756



                                    4



Stafanie Taylor



WI

746



                                    5



Meg Lanning



AUS

723



                                    6



Amy Satterthwaite



NZ

715



                                    7



Smriti Mandhana



IND

710



                                    8



Mithali Raj



IND

709



                                    9




This player has moved up in the rankings since the previous rankings update



Natalie Sciver



ENG

685



                                    10




This player has moved up in the rankings since the previous rankings update



Laura Wolvaardt



SA

683




Full Table


Last updated: 10. April 2021





wodi
ODI Bowling Rankings




Share
















URL Copied








                        1



Jess Jonassen


AUS
808













Pos
Player
Team
Rating





                                    2



Megan Schutt



AUS

762



                                    3



Marizanne Kapp



SA

747



                                    4



Shabnim Ismail



SA

717



                                    5



Jhulan Goswami



IND

681



                                    6



Katherine Brunt



ENG

655



                                    7




This player has moved up in the rankings since the previous rankings update



Poonam Yadav



IND

641



                                    8




This player has moved up in the rankings since the previous rankings update



Ayabonga Khaka



SA

638



                                    9




This player has moved down in the rankings since the previous rankings update



Ellyse Perry



AUS

616



                                    10



Shikha Pandey



IND

610




Full Table


Last updated: 10. April 2021





wodi
ODI All-Rounder Rankings




Share
















URL Copied








                        1




This player has moved up in the rankings since the previous rankings update



Marizanne Kapp


SA
418













Pos
Player
Team
Rating










This player has moved down in the rankings since the previous rankings update



Ellyse Perry



AUS

418



                                    3



Stafanie Taylor



WI

410



                                    4



Natalie Sciver



ENG

349



                                    5



Deepti Sharma



IND

343



                                    6



Jess Jonassen



AUS

307



                                    7



Ashleigh Gardner



AUS

252



                                    8




This player has moved up in the rankings since the previous rankings update



Dane van Niekerk



SA

243



                                    9




This player has moved down in the rankings since the previous rankings update



Sophie Devine



NZ

242



                                    10




This player has moved down in the rankings since the previous rankings update



Amelia Kerr



NZ

236




Full Table


Last updated: 10. April 2021

In [17]:
#Top 10 women’s ODI all-rounder along with the records of their team and rating

url = "https://www.icc-cricket.com/rankings/womens/player-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > div > div > div:nth-child(3) > div")
for a in anchors:
    print(a.text)

wodi
ODI All-Rounder Rankings




Share
















URL Copied








                        1




This player has moved up in the rankings since the previous rankings update



Marizanne Kapp


SA
418













Pos
Player
Team
Rating










This player has moved down in the rankings since the previous rankings update



Ellyse Perry



AUS

418



                                    3



Stafanie Taylor



WI

410



                                    4



Natalie Sciver



ENG

349



                                    5



Deepti Sharma



IND

343



                                    6



Jess Jonassen



AUS

307



                                    7



Ashleigh Gardner



AUS

252



                                    8




This player has moved up in the rankings since the previous rankings update



Dane van Niekerk



SA

243



                                    9




This player has moved down in the rankings since the previous rankings update



Sophie Devine



NZ

242



                                    10




This player has moved down in the rankings since the previous rankings update



Amelia Kerr



NZ

236




Full Table

In [290]:
maindiv = soup.select("#batsmen-tests div.text-center")
for d in maindiv[1:]:
    row_data = u",".join(s.strip() for s in filter(None, (t.find(text=True, recursive=False) for t in d.find_all())))
    if row_data:
        print(row_data)

# python program to scrape details of all the mobile phones under Rs. 20,000 listed on Amazon.in. The 
scraped data should include Product Name, Price, Image URL and Average Rating.

# python program to extract information about the local weather from the National Weather Service 
website of USA, https://www.weather.gov/ for the city, San Francisco. You need to extract data about 7 day

In [275]:
#7days weather info

url = "https://forecast.weather.gov/MapClick.php?lon=-122.49674&lat=37.72964#.YLN2F43itPZ"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#detailed-forecast-body")
for a in anchors:
    print(a.text)

TodaySunny, with a high near 68. West wind 5 to 11 mph. TonightPartly cloudy, with a low around 52. South southwest wind 6 to 9 mph. Memorial DaySunny, with a high near 73. Light south southwest wind becoming west southwest 8 to 13 mph in the afternoon. Monday NightPartly cloudy, with a low around 52. Southwest wind 11 to 14 mph. TuesdayMostly sunny, with a high near 64. Southwest wind 10 to 16 mph, with gusts as high as 21 mph. Tuesday NightMostly cloudy, with a low around 52.WednesdayPartly sunny, with a high near 59.Wednesday NightMostly cloudy, with a low around 52.ThursdayMostly sunny, with a high near 62.Thursday NightMostly cloudy, with a low around 53.FridayMostly sunny, with a high near 62.Friday NightPartly cloudy, with a low around 52.SaturdaySunny, with a high near 64.

In [288]:
maindiv = soup.select("#detailed-forecast-body > div:nth-child(1) > div.col-sm-2.forecast-label")
for d in maindiv[1:]:
    row_data = u",".join(s.strip() for s in filter(None, (t.find(text=True, recursive=False) for t in d.find_all())))
    if row_data:
        print(row_data)

In [268]:
#Extracting all the information from the page

page = requests.get("https://forecast.weather.gov/MapClick.php?lon=-122.49674&lat=37.72964#.YLN2F43itPZ")
soup = BeautifulSoup(page.content, 'html.parser')
seven_day = soup.find(id="seven-day-forecast")
forecast_items = seven_day.find_all(class_="tombstone-container")
tonight = forecast_items[0]
print(tonight.prettify())

<div class="tombstone-container">
 <p class="period-name">
  Today
  <br/>
  <br/>
 </p>
 <p>
  <img alt="Today: Sunny, with a high near 68. West wind 5 to 11 mph. " class="forecast-icon" src="newimages/medium/few.png" title="Today: Sunny, with a high near 68. West wind 5 to 11 mph. "/>
 </p>
 <p class="short-desc">
  Sunny
 </p>
 <p class="temp temp-high">
  High: 68 °F
 </p>
</div>

In [269]:
period = tonight.find(class_="period-name").get_text()
short_desc = tonight.find(class_="short-desc").get_text()
temp = tonight.find(class_="temp").get_text()
print(period)
print(short_desc)
print(temp)

Today
Sunny
High: 68 °F

In [270]:
img = tonight.find("img")
desc = img['title']
print(desc)

Today: Sunny, with a high near 68. West wind 5 to 11 mph.

In [271]:
period_tags = seven_day.select(".tombstone-container .period-name")
periods = [pt.get_text() for pt in period_tags]
periods

['Today',
 'Tonight',
 'MemorialDay',
 'MondayNight',
 'Tuesday',
 'TuesdayNight',
 'Wednesday',
 'WednesdayNight',
 'Thursday']

In [272]:
short_descs = [sd.get_text() for sd in seven_day.select(".tombstone-container .short-desc")]
temps = [t.get_text() for t in seven_day.select(".tombstone-container .temp")]
descs = [d["title"] for d in seven_day.select(".tombstone-container img")]

In [273]:
print(short_descs)
print(temps)
print(descs)

['Sunny', 'Partly Cloudy', 'Sunny', 'Partly Cloudy', 'Mostly Sunny', 'Mostly Cloudy', 'Partly Sunny', 'Mostly Cloudy', 'Mostly Sunny']
['High: 68 °F', 'Low: 52 °F', 'High: 73 °F', 'Low: 52 °F', 'High: 64 °F', 'Low: 52 °F', 'High: 59 °F', 'Low: 52 °F', 'High: 62 °F']
['Today: Sunny, with a high near 68. West wind 5 to 11 mph. ', 'Tonight: Partly cloudy, with a low around 52. South southwest wind 6 to 9 mph. ', 'Memorial Day: Sunny, with a high near 73. Light south southwest wind becoming west southwest 8 to 13 mph in the afternoon. ', 'Monday Night: Partly cloudy, with a low around 52. Southwest wind 11 to 14 mph. ', 'Tuesday: Mostly sunny, with a high near 64. Southwest wind 10 to 16 mph, with gusts as high as 21 mph. ', 'Tuesday Night: Mostly cloudy, with a low around 52.', 'Wednesday: Partly sunny, with a high near 59.', 'Wednesday Night: Mostly cloudy, with a low around 52.', 'Thursday: Mostly sunny, with a high near 62.']

In [274]:
import pandas as pd
weather = pd.DataFrame({
    "period": periods,
    "short_desc": short_descs,
    "temp": temps,
    "desc":descs
})
weather

,period,short_desc,temp,desc
0,Today,Sunny,High: 68 °F,"Today: Sunny, with a high near 68. West wind 5..."
1,Tonight,Partly Cloudy,Low: 52 °F,"Tonight: Partly cloudy, with a low around 52. ..."
2,MemorialDay,Sunny,High: 73 °F,"Memorial Day: Sunny, with a high near 73. Ligh..."
3,MondayNight,Partly Cloudy,Low: 52 °F,"Monday Night: Partly cloudy, with a low around..."
4,Tuesday,Mostly Sunny,High: 64 °F,"Tuesday: Mostly sunny, with a high near 64. So..."
5,TuesdayNight,Mostly Cloudy,Low: 52 °F,"Tuesday Night: Mostly cloudy, with a low aroun..."
6,Wednesday,Partly Sunny,High: 59 °F,"Wednesday: Partly sunny, with a high near 59."
7,WednesdayNight,Mostly Cloudy,Low: 52 °F,"Wednesday Night: Mostly cloudy, with a low aro..."
8,Thursday,Mostly Sunny,High: 62 °F,"Thursday: Mostly sunny, with a high near 62."

# python program to scrape fresher job listings from ‘https://internshala.com/’. It should include job title, 
company name, CTC, and apply date