# Python Web Scraping: Extract and display all the header tags from en.wikipedia.org/wiki/Main_Page

In [4]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import os

In [5]:
page=requests.get('https://en.wikipedia.org/wiki/Main_Page')
page

In [6]:
html = urlopen('https://en.wikipedia.org/wiki/Main_Page')
bs = BeautifulSoup(html, "html.parser")
titles = bs.find_all(['h1', 'h2','h3','h4','h5','h6'])
print('List all the header tags :', *titles, sep='\n\n')

List all the header tags :

<h1 class="firstHeading" id="firstHeading">Main Page</h1>

<h2 class="mp-h2" id="mp-tfa-h2"><span id="From_today.27s_featured_article"></span><span class="mw-headline" id="From_today's_featured_article">From today's featured article</span></h2>

<h2 class="mp-h2" id="mp-dyk-h2"><span class="mw-headline" id="Did_you_know_...">Did you know ...</span></h2>

<h2 class="mp-h2" id="mp-itn-h2"><span class="mw-headline" id="In_the_news">In the news</span></h2>

<h2 class="mp-h2" id="mp-otd-h2"><span class="mw-headline" id="On_this_day">On this day</span></h2>

<h2 class="mp-h2" id="mp-tfp-h2"><span id="Today.27s_featured_picture"></span><span class="mw-headline" id="Today's_featured_picture">Today's featured picture</span></h2>

<h2 class="mp-h2" id="mp-other"><span class="mw-headline" id="Other_areas_of_Wikipedia">Other areas of Wikipedia</span></h2>

<h2 class="mp-h2" id="mp-sister"><span id="Wikipedia.27s_sister_projects"></span><span class="mw-headline" id="Wikipedia's_sister_projects">Wikipedia's sister projects</span></h2>

<h2 class="mp-h2" id="mp-lang"><span class="mw-headline" id="Wikipedia_languages">Wikipedia languages</span></h2>

<h2>Navigation menu</h2>

<h3 class="vector-menu-heading" id="p-personal-label">
<span>Personal tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-namespaces-label">
<span>Namespaces</span>
</h3>

<h3 class="vector-menu-heading" id="p-variants-label">
<span>Variants</span>
</h3>

<h3 class="vector-menu-heading" id="p-views-label">
<span>Views</span>
</h3>

<h3 class="vector-menu-heading" id="p-cactions-label">
<span>More</span>
</h3>

<h3>
<label for="searchInput">Search</label>
</h3>

<h3 class="vector-menu-heading" id="p-navigation-label">
<span>Navigation</span>
</h3>

<h3 class="vector-menu-heading" id="p-interaction-label">
<span>Contribute</span>
</h3>

<h3 class="vector-menu-heading" id="p-tb-label">
<span>Tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-coll-print_export-label">
<span>Print/export</span>
</h3>

<h3 class="vector-menu-heading" id="p-wikibase-otherprojects-label">
<span>In other projects</span>
</h3>

<h3 class="vector-menu-heading" id="p-lang-label">
<span>Languages</span>
</h3>

# python program to display IMDB’s Top rated 100 movies’ data (i.e. Name, IMDB rating, Year of release) and make data frame.

In [7]:
df = pd.read_csv('Top 100 Movies List.csv')
print("Columns of the DataFrame:")
print(df.columns)

Columns of the DataFrame:
Index(['Position', 'Const', 'Created', 'Modified', 'Description', 'Title',
       'URL', 'Title Type', 'IMDb Rating', 'Runtime (mins)', 'Year', 'Genres',
       'Num Votes', 'Release Date', 'Directors'],
      dtype='object')

In [8]:
df

,Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
0,1,tt0111161,2019-11-21,2019-11-21,NaN,The Shawshank Redemption,https://www.imdb.com/title/tt0111161/,movie,9.3,142,1994,Drama,2395359,1994-09-10,Frank Darabont
1,2,tt0068646,2019-11-21,2019-11-21,NaN,The Godfather,https://www.imdb.com/title/tt0068646/,movie,9.2,175,1972,"Crime, Drama",1659267,1972-03-14,Francis Ford Coppola
2,3,tt0071562,2019-11-21,2019-11-21,NaN,The Godfather: Part II,https://www.imdb.com/title/tt0071562/,movie,9.0,202,1974,"Crime, Drama",1153446,1974-12-12,Francis Ford Coppola
3,4,tt0468569,2019-11-21,2019-11-21,NaN,The Dark Knight,https://www.imdb.com/title/tt0468569/,movie,9.0,152,2008,"Action, Crime, Drama, Thriller",2357045,2008-07-14,Christopher Nolan
4,5,tt0050083,2019-11-21,2019-11-21,NaN,12 Angry Men,https://www.imdb.com/title/tt0050083/,movie,9.0,96,1957,"Crime, Drama",706419,1957-04-10,Sidney Lumet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,tt0053125,2019-11-21,2019-11-21,NaN,North by Northwest,https://www.imdb.com/title/tt0053125/,movie,8.3,136,1959,"Adventure, Mystery, Thriller",303925,1959-07-01,Alfred Hitchcock
96,97,tt0066921,2019-11-21,2019-11-21,NaN,A Clockwork Orange,https://www.imdb.com/title/tt0066921/,movie,8.3,136,1971,"Crime, Drama, Sci-Fi",769919,1971-12-19,Stanley Kubrick
97,98,tt0208092,2019-11-21,2019-11-21,NaN,Snatch,https://www.imdb.com/title/tt0208092/,movie,8.3,104,2000,"Comedy, Crime",794621,2000-08-23,Guy Ritchie
98,99,tt0211915,2019-11-21,2019-11-21,NaN,Le fabuleux destin d'Amélie Poulain,https://www.imdb.com/title/tt0211915/,movie,8.3,122,2001,"Comedy, Romance",713713,2001-04-25,Jean-Pierre Jeunet
99,100,tt0012349,2019-11-21,2019-11-21,NaN,The Kid,https://www.imdb.com/title/tt0012349/,movie,8.3,68,1921,"Comedy, Drama, Family",116284,1921-01-16,Charles Chaplin

# python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. Name, IMDB rating, Year 
of release) and make data frame.

In [9]:
df = pd.read_csv('IMDB Top 100 Hindi Movies.csv')
print("Columns of the DataFrame:")
print(df.columns)

Columns of the DataFrame:
Index(['Position', 'Const', 'Created', 'Modified', 'Description', 'Title',
       'URL', 'Title Type', 'IMDb Rating', 'Runtime (mins)', 'Year', 'Genres',
       'Num Votes', 'Release Date', 'Directors'],
      dtype='object')

In [10]:
df

,Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors
0,1,tt0405508,2012-07-24,2012-10-07,[b][link=http://www.youtube.com/watch?v=AK28V4...,Rang De Basanti,https://www.imdb.com/title/tt0405508/,movie,8.1,167,2006,"Comedy, Crime, Drama",114035,2006-01-26,Rakeysh Omprakash Mehra
1,2,tt1187043,2012-07-24,2012-10-07,Highest grosser in Bollywood history\n\n[b][li...,3 Idiots,https://www.imdb.com/title/tt1187043/,movie,8.4,170,2009,"Comedy, Drama",354884,2009-12-23,Rajkumar Hirani
2,3,tt0986264,2012-07-24,2012-10-07,[b][link=http://www.youtube.com/watch?v=2VdZUj...,Taare Zameen Par,https://www.imdb.com/title/tt0986264/,movie,8.4,165,2007,"Drama, Family",174559,2007-12-21,"Aamir Khan, Amole Gupte"
3,4,tt0292490,2012-07-24,2012-10-07,[b][link=http://www.youtube.com/watch?v=m13b25...,Dil Chahta Hai,https://www.imdb.com/title/tt0292490/,movie,8.1,183,2001,"Comedy, Drama, Romance",67814,2001-08-10,Farhan Akhtar
4,5,tt0367110,2012-07-24,2012-10-07,[b][link=http://www.youtube.com/watch?v=NC7Guo...,"Swades: We, the People",https://www.imdb.com/title/tt0367110/,movie,8.2,210,2004,Drama,84788,2004-12-17,Ashutosh Gowariker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,tt1324059,2013-08-25,2013-08-25,NaN,Wake Up Sid,https://www.imdb.com/title/tt1324059/,movie,7.6,138,2009,"Comedy, Drama, Romance",28921,2009-10-02,Ayan Mukherjee
96,97,tt0114234,2012-07-25,2012-07-25,NaN,Rangeela,https://www.imdb.com/title/tt0114234/,movie,7.5,142,1995,"Comedy, Drama, Musical, Romance",9326,1995-09-08,Ram Gopal Varma
97,98,tt0076696,2012-07-25,2012-10-09,From the legendary Oscar winning director Sat...,Shatranj Ke Khilari,https://www.imdb.com/title/tt0076696/,movie,7.7,129,1977,"Comedy, Drama, History",3256,1977-03-10,Satyajit Ray
98,99,tt1926313,2012-07-25,2012-10-07,[b][link=http://www.youtube.com/watch?v=7pFE44...,Pyaar Ka Punchnama,https://www.imdb.com/title/tt1926313/,movie,7.6,149,2011,"Comedy, Drama, Romance",20241,2011-05-20,Luv Ranjan
99,100,tt0352314,2013-09-23,2013-09-23,NaN,Ek Hasina Thi,https://www.imdb.com/title/tt0352314/,movie,7.5,120,2004,"Crime, Drama, Mystery, Thriller",6959,2004-01-16,Sriram Raghavan

# python program to scrap book name, author name, genre and book review of any 5 books from 
‘www.bookpage.com

In [11]:
## single book name

url = "https://bookpage.com/"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

title = soup.select("#heroCarousel > div.carousel-inner > div.item.active > div > div.span6.hero-text > h4 > a")

for a in title:
    print(a.text)

Casey McQuiston

In [12]:
url = "https://bookpage.com/"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

title = soup.select("#heroCarousel > div.carousel-inner > div:nth-child(2) > div > div.span6.hero-text > h4 > a")
for a in title:
    print(a.text)

Audiobook Month

In [13]:
url = "https://bookpage.com/"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

title = soup.select("#heroCarousel > div.carousel-inner > div:nth-child(3) > div > div.span6.hero-text > h4")
for a in title:
    print(a.text)

Rita Williams-Garcia

In [14]:
url = "https://bookpage.com/features/26174-hold-list-bookshelf-meet-cute-fiction#.YLSo4YXitPY"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

title = soup.select("body > div:nth-child(7) > div.page-content > div > div.row-fluid.articles-block.homepage-features > div:nth-child(1) > div > div > div.content > p.sans.bold")
for a in title:
    print(a.text)

# python program to scrape cricket rankings from ‘www.icc-cricket.com’. You have to scrape:

In [15]:
#Top 10 ODI teams in men’s cricket along with the records for matches, points and rating.

import sys,requests,csv,io
from bs4 import BeautifulSoup
from urllib.parse import urljoin

url = "https://www.icc-cricket.com/rankings/mens/team-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > section > div.rankings-block__container.full.rankings-table")
for a in anchors:
    print(a.text)

Pos

Team
T


Matches
M


Points
P


Rating
R





1


New Zealand
NZ

17
2,054

                            121





2


Australia
AUS

25
2,945
118


3


India
IND

29
3,344
115


4


England
ENG

27
3,100
115


5


South Africa
SA

20
2,137
107


6


Pakistan
PAK

24
2,323
97


7


Bangladesh
BAN

27
2,438
90


8


West Indies
WI

27
2,222
82


9


Sri Lanka
SL

24
1,876
78


10


Afghanistan
AFG

17
1,054
62


11


Netherlands
NED

5
249
50


12


Ireland
IRE

19
807
42


13


Zimbabwe
ZIM

15
588
39


14


Scotland
SCO

7
258
37


15


Oman
OMA

7
240
34


16


Nepal
NEP

5
119
24


17


UAE
UAE

9
190
21


18


Namibia
NAM

6
97
16


19


United States
USA

8
93
12


20


Papua New Guinea
PNG

5
0
0

In [16]:
#Top 10 ODI Batsmen in men along with the records of their team and rating

url = "https://www.icc-cricket.com/rankings/mens/player-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > section:nth-child(2) > div.u-negative-wrapper-tab.uniform-grid.touch-scroll-list--tablet > div:nth-child(1) > div")
for a in anchors:
    print(a.text)

odi
ODI Batting Rankings




Share
















URL Copied








                        1



Babar Azam


PAK
865













Pos
Player
Team
Rating





                                    2



Virat Kohli



IND

857



                                    3



Rohit Sharma



IND

825



                                    4



Ross Taylor



NZ

801



                                    5



Aaron Finch



AUS

791



                                    6



Jonny Bairstow



ENG

785



                                    7



Fakhar Zaman



PAK

778







Francois du Plessis



SA

778



                                    9



David Warner



AUS

773







Shai Hope



WI

773




Full Table

In [17]:
#Top 10 ODI bowlers along with the records of their team and rating.

url = "https://www.icc-cricket.com/rankings/mens/player-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > section:nth-child(2) > div.u-negative-wrapper-tab.uniform-grid.touch-scroll-list--tablet > div:nth-child(2) > div")
for a in anchors:
    print(a.text)

odi
ODI Bowling Rankings




Share
















URL Copied








                        1



Trent Boult


NZ
737













Pos
Player
Team
Rating





                                    2



Mehedi Hasan



BAN

713



                                    3



Mujeeb Ur Rahman



AFG

708



                                    4



Matt Henry



NZ

691



                                    5



Jasprit Bumrah



IND

690



                                    6



Kagiso Rabada



SA

666



                                    7



Chris Woakes



ENG

665



                                    8



Josh Hazlewood



AUS

660



                                    9




This player has moved up in the rankings since the previous rankings update



Pat Cummins



AUS

646



                                    10




This player has moved down in the rankings since the previous rankings update



Mustafizur Rahman



BAN

645




Full Table

# python program to scrape cricket rankings from ‘www.icc-cricket.com’. You have to scrape:

In [18]:
#Top 10 ODI teams in women’s cricket along with the records for matches, points and rating

url = "https://www.icc-cricket.com/rankings/womens/team-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > section")
for a in anchors:
    print(a.text)

wodi
Women's ODI Rankings


Last updated (GMT) - 11 Apr 2021
Developed by David Kendix





Pos

Team
T


Matches
M


Points
P


Rating
R





1


Australia
AUS

18
2,955

                            164





2


South Africa
SA

24
2,828
118


3


England
ENG

17
1,993
117


4


India
IND

20
2,226
111


5


New Zealand
NZ

21
1,947
93


6


West Indies
WI

12
1,025
85


7


Pakistan
PAK

15
1,101
73


8


Bangladesh
BAN

5
306
61


9


Sri Lanka
SL

11
519
47


10


Ireland
IRE

2
25
13

In [19]:
#Top 10 women’s ODI players along with the records of their team and rating.


url = "https://www.icc-cricket.com/rankings/womens/player-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > div > div")
for a in anchors:
    print(a.text)

wodi
ODI Batting Rankings




Share
















URL Copied








                        1



Tammy Beaumont


ENG
765













Pos
Player
Team
Rating





                                    2



Lizelle Lee



SA

758



                                    3



Alyssa Healy



AUS

756



                                    4



Stafanie Taylor



WI

746



                                    5



Meg Lanning



AUS

723



                                    6



Amy Satterthwaite



NZ

715



                                    7



Smriti Mandhana



IND

710



                                    8



Mithali Raj



IND

709



                                    9




This player has moved up in the rankings since the previous rankings update



Natalie Sciver



ENG

685



                                    10




This player has moved up in the rankings since the previous rankings update



Laura Wolvaardt



SA

683




Full Table


Last updated: 10. April 2021





wodi
ODI Bowling Rankings




Share
















URL Copied








                        1



Jess Jonassen


AUS
808













Pos
Player
Team
Rating





                                    2



Megan Schutt



AUS

762



                                    3



Marizanne Kapp



SA

747



                                    4



Shabnim Ismail



SA

717



                                    5



Jhulan Goswami



IND

681



                                    6



Katherine Brunt



ENG

655



                                    7




This player has moved up in the rankings since the previous rankings update



Poonam Yadav



IND

641



                                    8




This player has moved up in the rankings since the previous rankings update



Ayabonga Khaka



SA

638



                                    9




This player has moved down in the rankings since the previous rankings update



Ellyse Perry



AUS

616



                                    10



Shikha Pandey



IND

610




Full Table


Last updated: 10. April 2021





wodi
ODI All-Rounder Rankings




Share
















URL Copied








                        1




This player has moved up in the rankings since the previous rankings update



Marizanne Kapp


SA
418













Pos
Player
Team
Rating










This player has moved down in the rankings since the previous rankings update



Ellyse Perry



AUS

418



                                    3



Stafanie Taylor



WI

410



                                    4



Natalie Sciver



ENG

349



                                    5



Deepti Sharma



IND

343



                                    6



Jess Jonassen



AUS

307



                                    7



Ashleigh Gardner



AUS

252



                                    8




This player has moved up in the rankings since the previous rankings update



Dane van Niekerk



SA

243



                                    9




This player has moved down in the rankings since the previous rankings update



Sophie Devine



NZ

242



                                    10




This player has moved down in the rankings since the previous rankings update



Amelia Kerr



NZ

236




Full Table


Last updated: 10. April 2021

In [20]:
#Top 10 women’s ODI all-rounder along with the records of their team and rating

url = "https://www.icc-cricket.com/rankings/womens/player-rankings/odi"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#main-content > div > div.l-sticky-side-nav__content > div > div > div > div > div:nth-child(3) > div")
for a in anchors:
    print(a.text)

wodi
ODI All-Rounder Rankings




Share
















URL Copied








                        1




This player has moved up in the rankings since the previous rankings update



Marizanne Kapp


SA
418













Pos
Player
Team
Rating










This player has moved down in the rankings since the previous rankings update



Ellyse Perry



AUS

418



                                    3



Stafanie Taylor



WI

410



                                    4



Natalie Sciver



ENG

349



                                    5



Deepti Sharma



IND

343



                                    6



Jess Jonassen



AUS

307



                                    7



Ashleigh Gardner



AUS

252



                                    8




This player has moved up in the rankings since the previous rankings update



Dane van Niekerk



SA

243



                                    9




This player has moved down in the rankings since the previous rankings update



Sophie Devine



NZ

242



                                    10




This player has moved down in the rankings since the previous rankings update



Amelia Kerr



NZ

236




Full Table

# python program to scrape details of all the mobile phones under Rs. 20,000 listed on Amazon.in. The 
scraped data should include Product Name, Price, Image URL and Average Rating.

In [41]:
#1st page data
url = "https://www.amazon.in/s?k=mobile+phones+under+Rs.+20%2C000&rh=n%3A1389432031&ref=nb_sb_noss"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#search > div.s-desktop-width-max.s-opposite-dir > div > div.s-matching-dir.sg-col-16-of-20.sg-col.sg-col-8-of-12.sg-col-12-of-16 > div > span:nth-child(4) > div.s-main-slot.s-result-list.s-search-results.sg-row")
for a in anchors:
    print(a.text)

Oppo A31 (Mystery Black, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers  4.2 out of 5 stars 13,038  ₹11,990₹11,990 ₹15,990₹15,990  Save ₹4,000 (25%)Save extra with No Cost EMI Get it by Tuesday, June 8FREE Delivery by Amazon




Samsung Galaxy M42 5G (Prism Dot Black, 6GB RAM, 128GB Storage)  4.1 out of 5 stars 1,117  Limited time deal  ₹21,999₹21,999 ₹24,999₹24,999  Save ₹3,000 (12%)Save extra with No Cost EMI Get it by Tomorrow, June 4FREE Delivery by Amazon




Best sellerin Smartphones  Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB Storage)  4.3 out of 5 stars 187,165  Limited time deal  ₹14,999₹14,999 ₹19,999₹19,999  Save ₹5,000 (25%)Save extra with No Cost EMI Get it by Thursday, June 10FREE Delivery by Amazon




Samsung Galaxy M12 (Black,6GB RAM, 128GB Storage) 6000 mAh with 8nm Processor | True 48 MP Quad Camera | 90Hz Refresh Rate  4.0 out of 5 stars 15,584  Limited time deal  ₹13,499₹13,499 ₹15,499₹15,499  Save ₹2,000 (13%)Save extra with No Cost EMIFREE Delivery by AmazonIn stock on June 6, 2021.




Vivo Y91i (Ocean Blue, 2GB RAM, 32GB Storage) with No Cost EMI/Additional Exchange Offers  4.1 out of 5 stars 3,982  ₹7,490₹7,490 ₹9,990₹9,990  Save ₹2,500 (25%)FREE Delivery by AmazonIn stock on July 14, 2021.




Redmi Note 9 (Pebble Grey, 4GB RAM 64GB Storage) - 48MP Quad Camera & Full HD+ Display  4.3 out of 5 stars 61,165  ₹10,999₹10,999 ₹14,999₹14,999  Save ₹4,000 (27%)₹500 coupon applied at checkoutSave ₹500  with coupon  Get it by Thursday, June 10FREE Delivery by Amazon




Oppo A31 (Fantasy White, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers  4.2 out of 5 stars 13,038  ₹11,990₹11,990 ₹15,990₹15,990  Save ₹4,000 (25%)Save extra with No Cost EMI FREE Delivery by Amazon




Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64GB Storage)  4.2 out of 5 stars 133,648  Limited time deal  ₹12,499₹12,499 ₹15,999₹15,999  Save ₹3,500 (22%)Save extra with No Cost EMI Get it by Saturday, June 5FREE Delivery by Amazon




Oppo A52 (Twilight Black, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers  4.2 out of 5 stars 10,378  ₹14,990₹14,990 ₹19,990₹19,990  Save ₹5,000 (25%) Get it by Tomorrow, June 4FREE Delivery by Amazon




Samsung Galaxy M11 (Black, 4GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers  4.1 out of 5 stars 1,406  ₹8,999₹8,999 ₹14,999₹14,999  Save ₹6,000 (40%) Get it by Tomorrow, June 4FREE Delivery by Amazon




Panasonic Eluga i7 (2GB RAM, 16GB Storage, Finger Print Sensor, 4000mAh Battery) (Black)  3.1 out of 5 stars 3,324  ₹5,000₹5,000 ₹10,999₹10,999  Save ₹5,999 (55%) Get it by Tomorrow, June 4FREE Delivery by Amazon




Nokia C3 Android 10 Smartphone with 2GB RAM 16GB Storage, All-Day Battery and Fingerprint Sensor – Nordic Blue  3.5 out of 5 stars 533  ₹6,199₹6,199 ₹8,499₹8,499  Save ₹2,300 (27%) Get it by Tomorrow, June 4FREE Delivery by Amazon




realme narzo 30A (Laser Black, 4GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers  4.2 out of 5 stars 55  ₹9,499₹9,499 ₹10,999₹10,999  Save ₹1,500 (14%)FREE Delivery by AmazonIn stock on June 6, 2021.




Oppo A54 (Starry Blue, 4GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers, 4gb, 64gb  3.8 out of 5 stars 22  ₹13,490₹13,490 ₹14,990₹14,990  Save ₹1,500 (10%)Save extra with No Cost EMI Get it by Tomorrow, June 4FREE Delivery by Amazon




Samsung Galaxy M11 (Metallic Blue, 4GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers  4.2 out of 5 stars 1,451  ₹8,999₹8,999 ₹14,999₹14,999  Save ₹6,000 (40%) Get it by Saturday, June 5FREE Delivery by Amazon




Redmi Note 10 (Aqua Green, 6GB RAM, 128GB Storage) - Amoled Dot Display | 48MP Sony Sensor IMX582 | Snapdragon 678 Processor  4.1 out of 5 stars 25,908  ₹14,499₹14,499 ₹17,999₹17,999  Save ₹3,500 (19%)Save extra with No Cost EMI Get it by Tomorrow, June 4FREE Delivery by Amazon




Mi 10i 5G (Pacific Sunrise, 6GB RAM, 128GB Storage) - 108MP Quad Camera | Snapdragon 750G Processor  4.2 out of 5 stars 15,402  ₹21,999₹21,999 ₹24,999₹24,999  Save ₹3,000 (12%)Save extra with No Cost EMI Get it by Tomorrow, June 4FREE Delivery by AmazonAmazon Certified: Alexa Built-in




Oppo A54 (Crystal Black, 4GB RAM, 64GB Storage) with No Cost EMI/Additional Exchange Offers, Large  3.8 out of 5 stars 22  ₹13,490₹13,490 ₹14,990₹14,990  Save ₹1,500 (10%)Save extra with No Cost EMI Get it by Tomorrow, June 4FREE Delivery by Amazon




Samsung Galaxy M31s (Mirage Blue, 8GB RAM, 128GB Storage)  4.3 out of 5 stars 66,768  Limited time deal  ₹20,499₹20,499 ₹24,999₹24,999  Save ₹4,500 (18%)Save extra with No Cost EMIFREE Delivery by AmazonIn stock on July 13, 2021.




OPPO A74 5G (Fluid Black, 6GB RAM, 128GB Storage)| 5000 mAh | 18W Fast Charge | 90Hz Super Amoled Display  4.1 out of 5 stars 608  ₹17,990₹17,990 ₹20,990₹20,990  Save ₹3,000 (14%)Save extra with No Cost EMI Get it by Saturday, June 5FREE Delivery by Amazon




Samsung Galaxy M31s (Mirage Black, 8GB RAM, 128GB Storage)  4.3 out of 5 stars 66,768  Limited time deal  ₹20,499₹20,499 ₹24,999₹24,999  Save ₹4,500 (18%)Save extra with No Cost EMI Get it by Saturday, June 5FREE Delivery by Amazon




OnePlus Nord 5G (Blue Marble, 12GB RAM, 256GB Storage)  4.3 out of 5 stars 72,446




Redmi Note 9 Pro Max (Champagne Gold, 6GB RAM, 64GB Storage) - 64MP Quad Camera & Latest 8nm Snapdragon 720G & Alexa Hands-Free  4.3 out of 5 stars 64,363  ₹14,999₹14,999 ₹18,999₹18,999  Save ₹4,000 (21%)Save extra with No Cost EMI Get it by Sunday, June 6FREE Delivery by AmazonAmazon Certified: Alexa Built-in




realme X7 (Space Silver, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers  4.2 out of 5 stars 89  Limited time deal  ₹19,999₹19,999 ₹21,999₹21,999  Save ₹2,000 (9%) Get it by Tomorrow, June 4FREE Delivery by Amazon





←Previous
1
2
3
...
9
Next→









Need help?






Visit the help section



 or




contact us

# python program to extract information about the local weather from the National Weather Service 
website of USA, https://www.weather.gov/ for the city, San Francisco. You need to extract data about 7 day

In [22]:
#7days weather info

url = "https://forecast.weather.gov/MapClick.php?lon=-122.49674&lat=37.72964#.YLN2F43itPZ"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#detailed-forecast-body")
for a in anchors:
    print(a.text)

OvernightPatchy drizzle.  Cloudy, with a low around 51. Southwest wind around 11 mph. ThursdayCloudy, then gradually becoming mostly sunny, with a high near 61. West southwest wind 10 to 13 mph. Thursday NightMostly cloudy, with a low around 52. West southwest wind around 11 mph. FridayMostly sunny, with a high near 61. West wind 11 to 14 mph, with gusts as high as 18 mph. Friday NightPartly cloudy, with a low around 51. West wind 11 to 14 mph. SaturdayMostly sunny, with a high near 62.Saturday NightPartly cloudy, with a low around 50.SundaySunny, with a high near 61.Sunday NightPartly cloudy, with a low around 51. Breezy. MondaySunny, with a high near 60. Breezy. Monday NightPartly cloudy, with a low around 50. Breezy. TuesdaySunny, with a high near 59.Tuesday NightPartly cloudy, with a low around 50. Breezy. WednesdayMostly sunny, with a high near 60.

In [24]:
#Extracting all the information from the page

page = requests.get("https://forecast.weather.gov/MapClick.php?lon=-122.49674&lat=37.72964#.YLN2F43itPZ")
soup = BeautifulSoup(page.content, 'html.parser')
seven_day = soup.find(id="seven-day-forecast")
forecast_items = seven_day.find_all(class_="tombstone-container")
tonight = forecast_items[0]
print(tonight.prettify())

<div class="tombstone-container">
 <p class="period-name">
  Overnight
  <br/>
  <br/>
 </p>
 <p>
  <img alt="Overnight: Patchy drizzle.  Cloudy, with a low around 51. Southwest wind around 11 mph. " class="forecast-icon" src="newimages/medium/nra.png" title="Overnight: Patchy drizzle.  Cloudy, with a low around 51. Southwest wind around 11 mph. "/>
 </p>
 <p class="short-desc">
  Patchy
  <br/>
  Drizzle
 </p>
 <p class="temp temp-low">
  Low: 51 °F
 </p>
</div>

In [25]:
period = tonight.find(class_="period-name").get_text()
short_desc = tonight.find(class_="short-desc").get_text()
temp = tonight.find(class_="temp").get_text()
print(period)
print(short_desc)
print(temp)

Overnight
PatchyDrizzle
Low: 51 °F

In [26]:
img = tonight.find("img")
desc = img['title']
print(desc)

Overnight: Patchy drizzle.  Cloudy, with a low around 51. Southwest wind around 11 mph.

In [27]:
period_tags = seven_day.select(".tombstone-container .period-name")
periods = [pt.get_text() for pt in period_tags]
periods

['Overnight',
 'Thursday',
 'ThursdayNight',
 'Friday',
 'FridayNight',
 'Saturday',
 'SaturdayNight',
 'Sunday',
 'SundayNight']

In [28]:
short_descs = [sd.get_text() for sd in seven_day.select(".tombstone-container .short-desc")]
temps = [t.get_text() for t in seven_day.select(".tombstone-container .temp")]
descs = [d["title"] for d in seven_day.select(".tombstone-container img")]

In [29]:
print(short_descs)
print(temps)
print(descs)

['PatchyDrizzle', 'DecreasingClouds', 'Mostly Cloudy', 'Mostly Sunny', 'Partly Cloudy', 'Mostly Sunny', 'Partly Cloudy', 'Sunny', 'Mostly Clearand Breezythen PartlyCloudy']
['Low: 51 °F', 'High: 61 °F', 'Low: 52 °F', 'High: 61 °F', 'Low: 51 °F', 'High: 62 °F', 'Low: 50 °F', 'High: 61 °F', 'Low: 51 °F']
['Overnight: Patchy drizzle.  Cloudy, with a low around 51. Southwest wind around 11 mph. ', 'Thursday: Cloudy, then gradually becoming mostly sunny, with a high near 61. West southwest wind 10 to 13 mph. ', 'Thursday Night: Mostly cloudy, with a low around 52. West southwest wind around 11 mph. ', 'Friday: Mostly sunny, with a high near 61. West wind 11 to 14 mph, with gusts as high as 18 mph. ', 'Friday Night: Partly cloudy, with a low around 51. West wind 11 to 14 mph. ', 'Saturday: Mostly sunny, with a high near 62.', 'Saturday Night: Partly cloudy, with a low around 50.', 'Sunday: Sunny, with a high near 61.', 'Sunday Night: Partly cloudy, with a low around 51. Breezy. ']

In [30]:
import pandas as pd
weather = pd.DataFrame({
    "period": periods,
    "short_desc": short_descs,
    "temp": temps,
    "desc":descs
})
weather

,period,short_desc,temp,desc
0,Overnight,PatchyDrizzle,Low: 51 °F,"Overnight: Patchy drizzle. Cloudy, with a low..."
1,Thursday,DecreasingClouds,High: 61 °F,"Thursday: Cloudy, then gradually becoming most..."
2,ThursdayNight,Mostly Cloudy,Low: 52 °F,"Thursday Night: Mostly cloudy, with a low arou..."
3,Friday,Mostly Sunny,High: 61 °F,"Friday: Mostly sunny, with a high near 61. Wes..."
4,FridayNight,Partly Cloudy,Low: 51 °F,"Friday Night: Partly cloudy, with a low around..."
5,Saturday,Mostly Sunny,High: 62 °F,"Saturday: Mostly sunny, with a high near 62."
6,SaturdayNight,Partly Cloudy,Low: 50 °F,"Saturday Night: Partly cloudy, with a low arou..."
7,Sunday,Sunny,High: 61 °F,"Sunday: Sunny, with a high near 61."
8,SundayNight,Mostly Clearand Breezythen PartlyCloudy,Low: 51 °F,"Sunday Night: Partly cloudy, with a low around..."

# python program to scrape fresher job listings from ‘https://internshala.com/’. It should include job title, 
company name, CTC, and apply date

In [31]:
#All Fresher job with details

url = "https://internshala.com/fresher-jobs"
r = requests.get(url)
r.content
soup = BeautifulSoup(r.content, "html.parser")

anchors = soup.select("#reference")
for a in anchors:
    print(a.text)

Filters



Category


Engineering
MBA
Computer Science
Humanities
Media
Creative Writing
Graphic Design
Finance
Civil Engineering
Chemical Engineering










Location


Mumbai
Bangalore
Delhi
Hyderabad
Pune
Chennai
Kolkata
Ahmedabad












Remote jobs






Also include internships







Clear all




                    OR





Search




























Junior Operations Executive


                        NCTI LLP









Bangalore







                                Start date



Starts Immediately





CTC


  3 - 3.6 LPA






Apply By

3 Jul' 21








                    Fresher Job

                    Fresher Job


View details









Internal Audit Associate


                        Transpeninsula LLC









Remote








                                Start date



Starts Immediately





CTC


  4.8 - 6 LPA






Apply By

3 Jul' 21








                    Fresher Job

                    Fresher Job


View details









Business Marketing Manager


                        MentorBoxx










Delhi, Pune, Mumbai







                                Start date



Starts Immediately





CTC


  4 - 8.5 LPA






Apply By

3 Jul' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









React Native Developer


                        Runners Planet










Remote








                                Start date



Starts Immediately





CTC


  6.62 - 7.95 LPA






Apply By

3 Jul' 21








                    Fresher Job

                    Fresher Job


View details









Research And Communications Associate


                        Institute For Governance, Policies & Politics










Delhi







                                Start date



Starts Immediately





CTC


  3 - 4.5 LPA






Apply By

3 Jul' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Data Scientist


                        ProtonAutoML









Remote








                                Start date



Starts Immediately





CTC


  3 - 3.5 LPA






Apply By

2 Jul' 21








                    Fresher Job

                    Fresher Job


View details









Data Science Django Developer


                        Markytics










Remote








                                Start date



Starts Immediately





CTC


  3 - 4.5 LPA






Apply By

2 Jul' 21








                    Fresher Job

                    Fresher Job


View details









Corporate Sales Associate


                        MiM-Essay










Delhi







                                Start date



Starts Immediately





CTC


  5 - 6.5 LPA






Apply By

2 Jul' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Full Stack Developer


                        Wondermail










Remote








                                Start date



Starts Immediately





CTC


  4 - 7 LPA






Apply By

1 Jul' 21








                    Fresher Job

                    Fresher Job


View details









Full Stack Developer (MERN)


                        Project Tinker










Ahmedabad, Gurgaon, Kolkata, Pune, Bangalore, Mumbai







                                Start date



Starts Immediately





CTC


  4 - 7.2 LPA






Apply By

1 Jul' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Business Development Executive


                        Kaizen Academy










Remote








                                Start date



Starts Immediately





CTC


  4.5 - 6 LPA






Apply By

1 Jul' 21








                    Fresher Job

                    Fresher Job


View details









Sales Development Representative


                        Amigobulls










Bangalore







                                Start date



Starts Immediately





CTC


  5.5 - 6.5 LPA






Apply By

1 Jul' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Graphic Designer


                        Underground Movement LLP










Ahmedabad







                                Start date



Starts Immediately





CTC


  3 - 5 LPA






Apply By

1 Jul' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Operations Executive


                        Alphacore Technologies Private Limited










Mumbai







                                Start date



Starts Immediately





CTC


  3 - 3.5 LPA






Apply By

1 Jul' 21








                    Fresher Job

                    Fresher Job


View details









Business Development Executive


                        Ruhcom Enterprises Private Limited









Remote








                                Start date



Starts Immediately





CTC


  3 LPA






Apply By

1 Jul' 21








                    Fresher Job

                    Fresher Job


View details









Admission Counselor (Sales)


                        Sky Education Group










Delhi, Ghaziabad, Noida







                                Start date



Starts Immediately





CTC


  3 LPA






Apply By

30 Jun' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Sales And Business Development Analyst


                        Mo's F&B Group










Delhi







                                Start date



Starts Immediately





CTC


  3 - 3.1 LPA






Apply By

30 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Growth Hacking Digital Marketer


                        Sleep Love









Hyderabad







                                Start date



Starts Immediately





CTC


  3 - 3.5 LPA






Apply By

30 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Junior Node.js Developer


                        Askadmissions.ai










Chennai, Bangalore, Hyderabad, Mumbai, Cochin







                                Start date



Starts Immediately





CTC


  3 - 4 LPA






Apply By

30 Jun' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Junior Digital Marketing Executive


                        Krivy










Ahmedabad







                                Start date



Starts Immediately





CTC


  3 LPA






Apply By

30 Jun' 21








                    Fresher Job

                    Fresher Job


View details









iOS App Developer


                        Ascentspark Software Private Limited










Kolkata







                                Start date



Starts Immediately





CTC


  3.6 - 7 LPA






Apply By

30 Jun' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Food Journalist


                        Truffle Nation









Delhi







                                Start date



Starts Immediately





CTC


  3 - 4.5 LPA






Apply By

30 Jun' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Junior Software Developer


                        Habitate Technologies Private Limited










Chennai







                                Start date



Starts Immediately





CTC


  5.2 - 7 LPA






Apply By

30 Jun' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Full Stack Developer


                        SoluLab










Remote








                                Start date



Starts Immediately





CTC


  3 - 5 LPA






Apply By

28 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Business Analyst


                        SoluLab










Remote








                                Start date



Starts Immediately





CTC


  3 - 4.2 LPA






Apply By

28 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Associate Full Stack Developer


                        REPOZITORY TECHNOLOGIES PRIVATE LIMITED









Abohar, Kaithal, Jind, Karnal, Kurukshetra, Sirsa, Yamuna Nagar, Churu, Hisar, Bhiwani







                                Start date



Starts Immediately





CTC


  3 - 3.6 LPA






Apply By

30 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Full Stack Engineer


                        Beehive Academy India










Remote








                                Start date



Starts Immediately





CTC


  4.2 - 8.2 LPA






Apply By

28 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Product Marketer


                        Bip










Remote








                                Start date



Starts Immediately





CTC


  3 - 6 LPA






Apply By

27 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Business Development Executive


                        Tabeazy









Remote








                                Start date



Starts Immediately





CTC


  3 LPA






Apply By

27 Jun' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Associate - Business Development


                        Leverage Edu










Delhi







                                Start date



Starts Immediately





CTC


  3.6 LPA






Apply By

27 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Research Analyst (Economics)


                        DEX-DEFT Research And Consulting OPC Private Limited









Delhi







                                Start date



Starts Immediately





CTC


  3 LPA






Apply By

30 Jun' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Machine Learning Engineer


                        AIMonk Labs Technology Limited









Bangalore







                                Start date



Starts Immediately





CTC


  5 - 6.5 LPA






Apply By

27 Jun' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Business Analyst


                        Kasper Consulting Private Limited










Gurgaon







                                Start date



Starts Immediately





CTC


  3.25 - 4 LPA






Apply By

26 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Business Development Executive (Inside Sales)


                        GREedge










Remote








                                Start date



Starts Immediately





CTC


  3.75 LPA






Apply By

26 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Business Development Associate


                        PEPKIDZ LEARNING









Bangalore







                                Start date



Starts Immediately





CTC


  3 - 4 LPA






Apply By

25 Jun' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Full Stack Software Engineer


                        Flair Labs










Mumbai







                                Start date



Starts Immediately





CTC


  3 - 4 LPA






Apply By

25 Jun' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Associate Front End Developer


                        Little Big Things










Remote








                                Start date



Starts Immediately





CTC


  3 - 5 LPA






Apply By

25 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Talent Acquisition Executive


                        CrewKarma










Remote








                                Start date



Starts Immediately





CTC


  3 - 5 LPA






Apply By

24 Jun' 21






                        The hiring for this job will be online and the company will provide work from home/ deferred joining till current COVID-19 situation improves







                    Fresher Job

                    Fresher Job


View details









Full Stack Developer


                        Codfirm









Remote








                                Start date



Starts Immediately





CTC


  5 - 8 LPA






Apply By

24 Jun' 21








                    Fresher Job

                    Fresher Job


View details









Backend Developer


                        WebMOBI










Remote








                                Start date



Starts Immediately





CTC


  3 LPA






Apply By

24 Jun' 21








                    Fresher Job

                    Fresher Job


View details











1 / 3

# End..